### ISSUE TITLE
Error when clicking In-kind Entitlements in QA Farmer Registry

### ISSUE THREAD

**Issue by adriancris** [openspp-project/openspp-registry#433]
_Description_:
Error when clicking in-kind entitlements in a program

_Actual Behavior_:
Error when clicking in-kind entitlements

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1770, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1797, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 2001, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 435, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/web/models/models.py", line 47, in web_search_read
    values_records = records.web_read(specification)
  File "/opt/odoo/addons/web/models/models.py", line 86, in web_read
    values_list: List[Dict] = self.read(fields_to_read, load=None)
  File "/opt/odoo/odoo/models.py", line 3540, in read
    return self._read_format(fnames=fields, load=load)
  File "/opt/odoo/odoo/models.py", line 3751, in _read_format
    vals[name] = convert(record[name], record, use_display_name)
  File "/opt/odoo/odoo/fields.py", line 3110, in convert_to_read
    return value.id
AttributeError: '_unknown' object has no attribute 'id'

The above server error caused the following client error:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://qa-farmer.newlogic.net/web/assets/debug/web.assets_web.js:9163:35)
    at App.handleError (https://qa-farmer.newlogic.net/web/assets/debug/web.assets_web.js:13354:20)
    at ComponentNode.initiateRender (https://qa-farmer.newlogic.net/web/assets/debug/web.assets_web.js:9959:26)

Caused by: RPC_ERROR://qa-farmer.newlogic.net/web/assets/debug/web.assets_web.js:27839:19)
    at XMLHttpRequest.<anonymous> (https://qa-farmer.newlogic.net/web/assets/debug/web.assets_web.js:27887:27)

_Expected Behavior_:
User should be able to click and navigate to the Entitlement table inside the program

_Instance_:
Farmer Registry QA Instance

Screenrecording:
https://github.com/OpenSPP/openspp-modules/assets/138551361/bf0b690a-95ec-438c-a746-0c3c841a44e6

**Comment by reichie020212** [comment]
Upon checking, this error has been fixed by this commit https://github.com/OpenSPP/openspp-modules/commit/dedb9f3998262c66ab1dc8edc035ce1e4b6bae58

**Comment by anthonymarkQA** [comment]
FIndings QA Passed

Group:
 default elligiblity + default
![image](https://github.com/user-attachments/assets/3e29c3f8-587b-4b0f-9d4e-55a7cfc609ad)

Group
Manual + cash
![image](https://github.com/user-attachments/assets/6386b6f7-b912-44ae-bbc6-d19cee21e134)


Individual:
tag based + in kind
![image](https://github.com/user-attachments/assets/86256725-b3e1-47e2-82d0-42c88ccb7339)
