### ISSUE TITLE
Error when creating a Group in QA Farmer Registry

### ISSUE THREAD

**Issue by adriancris** [openspp-project/openspp-registry#454]
_Error_:

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1770, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1797, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 2001, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/web/models/models.py", line 73, in web_save
    self = self.create(vals)
  File "/opt/odoo/addons/spp_audit_log/tools/decorator.py", line 34, in audit_create
    result = audit_create.origin(self, vals)
  File "<decorator-gen-237>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 414, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/addons/spp_farmer_registry_base/models/farm.py", line 45, in create
    self.create_update_farmer(farm)
  File "/opt/odoo/addons/spp_farmer_registry_base/models/farm.py", line 142, in create_update_farmer
    individual = self.env["res.partner"].create(individual_vals)
  File "/opt/odoo/addons/spp_audit_log/tools/decorator.py", line 38, in audit_create
    new_values = record.read(load="_classic_write")
  File "/opt/odoo/odoo/models.py", line 3539, in read
    self._origin.fetch(fields)
  File "/opt/odoo/odoo/models.py", line 3812, in fetch
    query = self.with_context(active_test=False)._search([('id', 'in', self.ids)])
  File "/opt/odoo/odoo/models.py", line 5395, in _search
    self._flush_search(domain, order=order)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 400, in _flush_search
    return super()._flush_search(domain, fields, order, seen)
  File "/opt/odoo/odoo/models.py", line 5365, in _flush_search
    self.env[model_name].flush_model(field_names)
  File "/opt/odoo/odoo/models.py", line 6304, in flush_model
    self._flush(fnames)
  File "/opt/odoo/odoo/models.py", line 6377, in _flush
    process(model, id_vals)
  File "/opt/odoo/odoo/models.py", line 6327, in process
    model.browse(ids)._write(vals)
  File "/opt/odoo/addons/spp_audit_log/tools/decorator.py", line 52, in audit_write
    old_values = self.sudo().with_context(allowed_company_ids=[]).read(load="_classic_write")
  File "/opt/odoo/odoo/models.py", line 3540, in read
    return self._read_format(fnames=fields, load=load)
  File "/opt/odoo/odoo/models.py", line 3751, in _read_format
    vals[name] = convert(record[name], record, use_display_name)
  File "/opt/odoo/odoo/models.py", line 6603, in __getitem__
    return self._fields[key].__get__(self, self.env.registry[self._name])
  File "/opt/odoo/odoo/fields.py", line 1207, in __get__
    self.compute_value(recs)
  File "/opt/odoo/odoo/fields.py", line 1389, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 424, in _compute_field_value
    return super()._compute_field_value(field)
  File "/opt/odoo/odoo/models.py", line 4875, in _compute_field_value
    fields.determine(field.compute, self)
  File "/opt/odoo/odoo/fields.py", line 102, in determine
    return needle(*args)
  File "/opt/odoo/addons/calendar/models/res_partner.py", line 20, in _compute_meeting_count
    result = self._compute_meeting()
  File "/opt/odoo/addons/calendar/models/res_partner.py", line 27, in _compute_meeting
    all_partners = self.with_context(active_test=False).search_fetch(
  File "/opt/odoo/odoo/models.py", line 1634, in search_fetch
    query = self._search(domain, offset=offset, limit=limit, order=order or self._order)
  File "/opt/odoo/odoo/models.py", line 5395, in _search
    self._flush_search(domain, order=order)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 400, in _flush_search
    return super()._flush_search(domain, fields, order, seen)
  File "/opt/odoo/odoo/models.py", line 5365, in _flush_search
    self.env[model_name].flush_model(field_names)
  File "/opt/odoo/odoo/models.py", line 6304, in flush_model
    self._flush(fnames)
  File "/opt/odoo/odoo/models.py", line 6377, in _flush
    process(model, id_vals)
  File "/opt/odoo/odoo/models.py", line 6327, in process
    model.browse(ids)._write(vals)
  File "/opt/odoo/addons/spp_audit_log/tools/decorator.py", line 57, in audit_write
    new_values = get_new_values(self)
  File "/opt/odoo/addons/spp_audit_log/tools/decorator.py", line 16, in get_new_values
    vals[fname] = records._fields[fname].convert_to_read(record[fname], record, use_display_name=False)
TypeError: GeoField.convert_to_read() got an unexpected keyword argument 'use_display_name'

The above server error caused the following client error:
RPC_ERROR://qa-farmer.newlogic.net/web/assets/debug/web.assets_web.js:27839:19)
    at XMLHttpRequest.<anonymous> (https://qa-farmer.newlogic.net/web/assets/debug/web.assets_web.js:27887:27)

_Screenshot_:
![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/42aaef35-e933-4bc9-ab3d-882a5dc97735)

**Comment by reichie020212** [comment]
@adriancris it seems that this instance is not yet updated since the fix for this issue is already in the 17.0 branch. We just need to update the instance

CC: @dasunhegoda

**Comment by reichie020212** [comment]
Already fixed

**Comment by anthonymarkQA** [comment]
Findings - QA Passed

Able to create group
![image](https://github.com/user-attachments/assets/21145ae9-9e8c-414a-b40d-9e6bf68587ad)
