### ISSUE TITLE
Invalid operation when creating a new Country Office

### ISSUE THREAD

**Issue by adriancris** [openspp-project/openspp-registry#455]
_Instance_:
ACF-DEV

_Steps to reproduce_:
1. Navigate to **Registry** > **Configuration** > **Country Office**.
2. Click **New** then provide a **Country Office Name**.
3. Click **Save manually**.

_Actual Behavior_:
Error after clicking Save manually.

_Expected Behavior_:
Should be able to create a new Country Office

_Screenshot_:
![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/dcb552ca-29fc-49e2-adb2-fc9bbadb32e2)

**Comment by reichie020212** [comment]
below are Red's findings:
- "stock" is having an error upon installation if "g2p_registry_base" is install and there are more than 1 company
- Error in the screenshot occured if "stock" and "g2p_registry_base" are installed.
- The cause of error is because of the `company_id` field in the file `g2p_registry_base/models/registrant.py` changing it's parameters to required=True and adding a default value. check below code
```
company_id = fields.Many2one("res.company", required=True, default=lambda self: self.env.company)
```
- originaly, `company_id` of `res.partner` is not required and doesn't have a default value. check below code
```
company_id = fields.Many2one('res.company', 'Company', index=True)
```
- this error shows because of a company checker function that will only execute if the model's attribute `_check_company_auto` is set to True
- "stock.warehouse" model's `_check_company_auto` is set to True that's why `_check_company` function of base Model is executing.
- `_check_company` checks if the res.company of a res.partner is the same as the res.company of the record that is being updated/created or if the res.company is False.
- because of the default value that was added in the `company_id` field, _check_company is raising an error since it is  neither the same company of the record nor it is blank.

**Comment by reichie020212** [comment]
@dasunhegoda @jeremi @gonzalesedwin1123 , above is my findings on this issue, i just have a question. Should we be the one to fix this issue or should it be the OpenG2P people?

**Comment by anthonymarkQA** [comment]
Findings: Returned to dev

Same issuem Upon creation of a country office , it will display an error
tested in acf dev instance


![Image](https://github.com/user-attachments/assets/1c3442b9-f557-400a-b310-2d55f06de5b5)

UncaughtPromiseError > OwlError
Uncaught Promise > An error occured in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    Error: An error occured in the owl lifecycle (see this Error's "cause" property)
        at handleError (https://acf-dev.newlogic-demo.com/web/assets/608a10d/web.assets_web.min.js:916:101)
        at App.handleError (https://acf-dev.newlogic-demo.com/web/assets/608a10d/web.assets_web.min.js:1543:29)
        at Fiber._render (https://acf-dev.newlogic-demo.com/web/assets/608a10d/web.assets_web.min.js:941:19)
        at Fiber.render (https://acf-dev.newlogic-demo.com/web/assets/608a10d/web.assets_web.min.js:939:6)
        at ComponentNode.initiateRender (https://acf-dev.newlogic-demo.com/web/assets/608a10d/web.assets_web.min.js:1007:47)

Caused by: EvalError: Can not evaluate python expression: (bool(parent_id != False))
    Error: Name 'parent_id' is not defined
    EvalError: Can not evaluate python expression: (bool(parent_id != False))
    Error: Name 'parent_id' is not defined
        at evaluateExpr (https://acf-dev.newlogic-demo.com/web/assets/608a10d/web.assets_web.min.js:3044:54)
        at evaluateBooleanExpr (https://acf-dev.newlogic-demo.com/web/assets/608a10d/web.assets_web.min.js:3047:8)
        at fieldVisualFeedback (https://acf-dev.newlogic-demo.com/web/assets/608a10d/web.assets_web.min.js:7668:129)
        at get className (https://acf-dev.newlogic-demo.com/web/assets/608a10d/web.assets_web.min.js:8719:576)
        at FormLabel.template (eval at compile (https://acf-dev.newlogic-demo.com/web/assets/608a10d/web.assets_web.min.js:1501:374), <anonymous>:12:20)
        at Fiber._render (https://acf-dev.newlogic-demo.com/web/assets/608a10d/web.assets_web.min.js:940:96)
        at Fiber.render (https://acf-dev.newlogic-demo.com/web/assets/608a10d/web.assets_web.min.js:939:6)
        at ComponentNode.initiateRender (https://acf-dev.newlogic-demo.com/web/assets/608a10d/web.assets_web.min.js:1007:47)

**Comment by anthonymarkQA** [comment]
Findings: QA Passed

Able to create and save changes for new company - pass
Able to edit existing company - pass
Should not be able to use already existing name as company name - pass
able to delete company - pass ( closest to deletion is by archiving the company) 
![image](https://github.com/user-attachments/assets/ee5022bc-737f-4cc9-abaa-919ee510413a)
