### ISSUE TITLE
Fix demo data generator of module spp_demo

### ISSUE THREAD

**Issue by reichie020212** [openspp-project/openspp-registry#600]
error `odoo.exceptions.ValidationError: Registration date must be later than the birth date.` is showing on the function `_generate_sample_data` of `spp_demo` module.

Please fix it.

**Comment by reichie020212** [comment]
Here is the tracestack

```
Traceback (most recent call last):
  File "/opt/odoo/auto/addons/queue_job/controllers/main.py", line 104, in runjob
    self._try_perform_job(env, job)
  File "/opt/odoo/auto/addons/queue_job/controllers/main.py", line 36, in _try_perform_job
    job.perform()
  File "/opt/odoo/auto/addons/queue_job/job.py", line 517, in perform
    self.result = self.func(*tuple(self.args), **self.kwargs)
  File "/opt/odoo/auto/addons/spp_demo/models/generate_group.py", line 168, in _generate_sample_data
    create_member_id = self.env["res.partner"].create(member)
  File "<decorator-gen-226>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 414, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/auto/addons/g2p_registry_membership/models/individual.py", line 47, in create
    res = super().create(vals_list)
  File "<decorator-gen-225>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 394, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 394, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo/auto/addons/g2p_registry_membership/models/group.py", line 42, in create
    new_record = super().create(values)
  File "<decorator-gen-205>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 414, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/auto/addons/account/models/partner.py", line 734, in create
    return super().create(vals_list)
  File "<decorator-gen-193>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/auto/addons/partner_autocomplete/models/res_partner.py", line 212, in create
    partners = super(ResPartner, self).create(vals_list)
  File "<decorator-gen-100>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/res_partner.py", line 752, in create
    partners = super(Partner, self).create(vals_list)
  File "<decorator-gen-137>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/auto/addons/mail/models/mail_thread.py", line 259, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-12>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4626, in create
    records = self._create(data_list)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4888, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 1462, in _validate_fields
    check(self)
  File "/opt/odoo/auto/addons/g2p_registry_base/models/registrant.py", line 83, in _check_registration_date
    raise ValidationError(error_message)
odoo.exceptions.ValidationError: Registration date must be later than the birth date.
```

**Comment by emjay0921** [comment]
## **Possible duplicate ticket**
This is connected to this Ticket: https://github.com/OpenSPP/openspp-modules/issues/627

**Comment by celinenilla** [comment]
@reichie020212 , can you please test if this still occurs after #627 ?

**Comment by reichie020212** [comment]
@celinenilla Upon testing it in my local, the error is not showing anymore.

**Comment by reichie020212** [comment]
Moving this ticket to Done
