### ISSUE TITLE
Sample data generation failure when "_check_registration_date" detects an invalid birth date

### ISSUE THREAD

**Issue by kneckinator** [openspp-project/openspp-registry#627]
When generating sample data, I quite often run into the issue "Registration date must be later than the birth date.".
This is easy to reproduce if I select a sample data size of 1000 or higher.
When this happens, the data generation fails and none of the so far generated data is available.
The bug is making is hard/tedious/impossible to create meaningful amounts of sample data, i.e 500,000 groups.

The configuration for 1000 groups looks like this:
![Image](https://github.com/user-attachments/assets/a5e65e53-e4f2-43c0-b3bc-ba1d4b162895)

Expected behavior:
The sample data generator should make sure that the generated birth date is later than the generated registration date.

Full traceback:
```
Traceback (most recent call last):
  File "/opt/odoo/auto/addons/queue_job/controllers/main.py", line 104, in runjob
    self._try_perform_job(env, job)
  File "/opt/odoo/auto/addons/queue_job/controllers/main.py", line 36, in _try_perform_job
    job.perform()
  File "/opt/odoo/auto/addons/queue_job/job.py", line 517, in perform
    self.result = self.func(*tuple(self.args), **self.kwargs)
  File "/opt/odoo/auto/addons/spp_demo/models/generate_group.py", line 178, in _generate_sample_data
    create_member_id = self.env["res.partner"].create(member)
  File "<decorator-gen-228>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 414, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/auto/addons/g2p_registry_membership/models/individual.py", line 47, in create
    res = super().create(vals_list)
  File "<decorator-gen-227>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 394, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 394, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo/auto/addons/g2p_registry_membership/models/group.py", line 42, in create
    new_record = super().create(values)
  File "<decorator-gen-207>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 414, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/auto/addons/account/models/partner.py", line 751, in create
    return super().create(vals_list)
  File "<decorator-gen-195>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/auto/addons/partner_autocomplete/models/res_partner.py", line 212, in create
    partners = super(ResPartner, self).create(vals_list)
  File "<decorator-gen-96>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/res_partner.py", line 752, in create
    partners = super(Partner, self).create(vals_list)
  File "<decorator-gen-139>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/auto/addons/mail/models/mail_thread.py", line 259, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-12>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4626, in create
    records = self._create(data_list)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4888, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 1462, in _validate_fields
    check(self)
  File "/opt/odoo/auto/addons/g2p_registry_base/models/registrant.py", line 83, in _check_registration_date
    raise ValidationError(error_message)
odoo.exceptions.ValidationError: Registration date must be later than the birth date.
```

**Comment by anthonymarkQA** [comment]
Findings: Returned to DEV
Tested in runboat instance with spmis configuration
instance ID:
b9c6f1b50-92d5-4151-b31d-2b012bf7f189

Unable to generate 1000 or more sample data as the job queue gets stuck at "starting" state
![image](https://github.com/user-attachments/assets/e9c02da2-efde-443e-b0c9-a56a22febbe5)

**Comment by kneckinator** [comment]
The issues with queues in #622 has not yet been fixed. You will have to test this in another instance @anthonymarkQA

**Comment by kneckinator** [comment]
I will test this with varying sample sizes; 100, 500, 1000, 10,000, 100,000.

**Comment by kneckinator** [comment]
Works well. Thanks @emjay0921 ! 🎉

**Comment by anthonymarkQA** [comment]
Findings: verified on a separate instance by @kneckinator 
With varying sample sizes 100, 500, 1000, 1013, 10,000, 100,000. 

a minor issue was found during sample size 1013- it generated 2000 demo data.
this will be handled on a separate tiicket.

Otherwise this ticket is QA passed.
Moving this ticket to done
