### ISSUE TITLE
Fix the issue with the "Hide Menus" access right

### ISSUE THREAD

**Issue by celinenilla** [openspp-project/openspp-registry#633]
The hiding of the default Odoo menus needs to be coded in a separate module so that it can be used for other implementations. The following specification provides the features required and the fixes with the current solution:

- [ ] Change the title of the "Hide Menus" access right to "Show non-OpenSPP menus".
- [ ] Remove the 2nd "Hide Menus" access right.
- [ ] Make the "Hide Menus" automatically assigned to new users.
- [ ] Do not set the "Hide Menus" access rights to superusers.
- [ ] Make the new module a dependency of spp_base (SPMIS) and spp_farmer_registry_base.

![Image](https://github.com/user-attachments/assets/1921c9b1-eb00-4167-83b4-5977bc0920f2)

**Comment by gonzalesedwin1123** [comment]
@celinenilla  can we have in this ticket the development of a common module for hiding the default Odoo menus and provide configuration UIs for the visibility of certain modules?

**Comment by celinenilla** [comment]
yes @gonzalesedwin1123, let's do that. can you please update the description?

**Comment by jannahadlaon** [comment]
Findings: **Return to dev**

Installing `spp_hide_menus` raises an error
![image](https://github.com/user-attachments/assets/9ba1bfc0-e53d-473b-8fd9-98ff303989c7)
![image](https://github.com/user-attachments/assets/39576a2a-b644-4cfb-9bcf-efe327ae0e3a)
@emjay0921 @gonzalesedwin1123 

Error message:
```
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1768, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1795, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1999, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-77>", line 2, in button_immediate_install
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 466, in button_immediate_install
    return self._button_immediate_function(self.env.registry[self._name].button_install)
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 590, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/opt/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/opt/odoo/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 480, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/opt/odoo/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/opt/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/odoo/odoo/tools/convert.py", line 623, in convert_file
    convert_csv_import(env, module, pathname, fp.read(), idref, mode, noupdate)
  File "/opt/odoo/odoo/tools/convert.py", line 669, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading spp_hide_menus failed: file spp_hide_menus/security/ir.model.access.csv could not be processed:
 No matching record found for external id 'g2p_registry_base.group_g2p_admin' in field 'Group'

The above server error caused the following client error:
RPC_ERROR://openspp-openspp-modules-jannah-633-b86cdbdd226c.runboatk8.newlogic-demo.com/web/assets/7c1f94c/web.assets_web.min.js:2870:163)
    at XMLHttpRequest.<anonymous> (http://openspp-openspp-modules-jannah-633-b86cdbdd226c.runboatk8.newlogic-demo.com/web/assets/7c1f94c/web.assets_web.min.js:2874:13)
```

**Comment by emjay0921** [comment]
Updated and moved back to QA. No additional review needed as there's just one line added in dependencies.

**Comment by jannahadlaon** [comment]
Findings: Return to devs

Hide Menu Configuration tab is working as expected (see video below)
https://drive.google.com/file/d/1IVnq85X_BnMizcARPaDnHOK48tlzwQrf/view?usp=sharing

However, when users activate **Show Non-OpenSPP Menu** by going to  to Settings > User & Companies > Users > Select a users >Access rights>  tick on **Show Non-OpenSPP Menu** then SAVE. 
The hidden menu are shown but in Hide Menu Configuration tab ( Activate Developer Mode > Settings > User & Companies > Hidden Menus) the state is still hidden.
![image](https://github.com/user-attachments/assets/c3482ffd-275d-4504-b113-c54298a3b843)
See video below:
https://drive.google.com/file/d/1xg10RM3QKYBEa7WpYgRo0GBLFnfzUcBY/view?usp=sharing

**Comment by emjay0921** [comment]
That is expected @jannahadlaon. As users with `Show Non-OpenSPP` Checked will show all hidden menus from the `Hidden Menus`. If this will become not hidden all users will see that menus.

**Comment by jannahadlaon** [comment]
Findings: QA PASSED

Issue mentioned above is expected.  

As per @emjay0921 explained: 

- Hide Menu Configuration tab ( Activate Developer Mode > Settings > User & Companies > Hidden Menus) affects all the users created by the admin.
- Show Non-OpenSPP Menu by going to to Settings > User & Companies > Users > Select a users >Access rights> tick on Show Non-OpenSPP Menu then SAVE, affects only the user.
