### ISSUE TITLE
Archiving multiple group records displays a validation error

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#637]
**Describe the bug**
Can be replicated in both QA SPMIS and QA FARMER generic.

When attempting to archive multiple groups from either instance. a validation error appears, this occurs if there are at least a head member on at least 2 of the groups you are trying to archive.

1. For spmis qa: "Only one Head is allowed per group"
2. For farmer registry qa: "Farm must have a head member"

**To Reproduce**

1. go to either instance farmer or spmis qa and login as admin
2. go to registry>groups,
3. click on checkbox beside "Name" to select all records
4. click on action>Archive>Click archive button
5. Notice a validation error will appear.

**Expected behavior**
Should be able to archive multiple records for either spmis qa or farmer qa configurations.

**Screenshots**
![image](https://github.com/user-attachments/assets/b03e4076-0815-4e68-980e-c76da9d8368e)

**Additional context**

🔔 Note: This ticket should address common considerations without including country-specific content. Please ensure all references are generic and applicable across various contexts.

**Comment by emjay0921** [comment]
PR in forked OpenG2P-Registry: https://github.com/OpenSPP/openg2p-registry/pull/3

**Comment by kneckinator** [comment]
@jannahadlaon as the OpenG2P/openg2p-registry PR has been merged, you can now test this in runboat by creating an instance for `openspp/openspp-modules` with the branch `17.0`.

**Comment by jannahadlaon** [comment]
Findings: **Testing blocked**

When trying to install **SPP STARTER**, error appears after clicking the **Done** button.
![image](https://github.com/user-attachments/assets/17824f8c-38d3-4f39-814a-4e7e6c709ee2)


```
Traceback (most recent call last):
  File "/opt/odoo/odoo/models.py", line 6519, in union
    if arg._name != self._name:
AttributeError: 'NoneType' object has no attribute '_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1768, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1795, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1999, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/data/odoo-addons-dir/spp_starter/wizards/spp_starter.py", line 163, in action_done
    modules = self._install_modules()
  File "/mnt/data/odoo-addons-dir/spp_starter/wizards/spp_starter.py", line 220, in _install_modules
    res |= find_module("spp_demo")
  File "/opt/odoo/odoo/models.py", line 6510, in __or__
    return self.union(other)
  File "/opt/odoo/odoo/models.py", line 6523, in union
    raise TypeError(f"unsupported operand types in: {self} | {arg!r}")
TypeError: unsupported operand types in: ir.module.module(600, 461, 516, 469, 472, 492) | None

The above server error caused the following client error:
RPC_ERROR://openspp-openspp-modules-jannah-637-b3b454e12bc4.runboatk8.newlogic-demo.com/web/assets/9ccc5e9/web.assets_web.min.js:2870:163)
    at XMLHttpRequest.<anonymous> (http://openspp-openspp-modules-jannah-637-b3b454e12bc4.runboatk8.newlogic-demo.com/web/assets/9ccc5e9/web.assets_web.min.js:2874:13)
```
cc: @emjay0921 @gonzalesedwin1123

**Comment by emjay0921** [comment]
Fix will be done in this ticket: https://github.com/OpenSPP/openspp-modules/issues/660. I will comment the PR here later.

**Comment by emjay0921** [comment]
Here's the PR needed to be able to test this: https://github.com/OpenSPP/openspp-modules/pull/661

**Comment by jannahadlaon** [comment]
Findings:
     FARMER - **QA PASSED**
     SP-MIS - **QA PASSED**
     
**STEPS**:
1. go to either instance FARMER or SP-MIS and login as admin
2. go to registry>groups,
3. click on checkbox beside "Name" to select all records
4. click on action>Archive>Click archive button
Verify that no error occur after archiving  for both FARMER and SP-MIS

cc: @emjay0921
