### ISSUE TITLE
Unable to install modules in QA SPMIS instance

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#677]
**Describe the bug**
When attempting to install spp_base and other modules, an odoo error appears:
Traceback error posted  below:

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/tools/convert.py", line 556, in _tag_root
    f(rec)
  File "/opt/odoo/odoo/tools/convert.py", line 456, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/opt/odoo/odoo/models.py", line 5087, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo/odoo/models.py", line 4998, in _load_records_create
    return self.create(values)
  File "<decorator-gen-195>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/addons/stock/models/stock_warehouse.py", line 126, in create
    warehouses = super().create(vals_list)
  File "<decorator-gen-12>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/models.py", line 4626, in create
    records = self._create(data_list)
  File "/opt/odoo/odoo/models.py", line 4814, in _create
    cr.execute(SQL(
  File "/opt/odoo/odoo/sql_db.py", line 332, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "stock_warehouse_warehouse_code_uniq"
DETAIL:  Key (code, company_id)=(WH, 1) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1783, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1810, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 2014, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 759, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-81>", line 2, in button_immediate_install
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 466, in button_immediate_install
    return self._button_immediate_function(self.env.registry[self._name].button_install)
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 590, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/opt/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/opt/odoo/odoo/modules/registry.py", line 114, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 480, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/opt/odoo/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/opt/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/odoo/odoo/tools/convert.py", line 627, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/opt/odoo/odoo/tools/convert.py", line 693, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo/odoo/tools/convert.py", line 613, in parse
    self._tag_root(de)
  File "/opt/odoo/odoo/tools/convert.py", line 556, in _tag_root
    f(rec)
  File "/opt/odoo/odoo/tools/convert.py", line 569, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /opt/odoo/addons/stock/data/stock_data.xml:84, somewhere inside
<record id="warehouse0" model="stock.warehouse">
            <field name="partner_id" ref="base.main_partner"/>
            <field name="code">WH</field>
        </record>

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (https://qa-sp-mis.newlogic.net/web/assets/9092da8/web.assets_web.min.js:2891:163)
        at XMLHttpRequest.<anonymous> (https://qa-sp-mis.newlogic.net/web/assets/9092da8/web.assets_web.min.js:2895:13)
**To Reproduce**
1. Go to SPMIS QA and login as admin
2. Go to apps and install spp_base or spp_program
3. Notice an odoo error appears
**Expected behavior**
Should be able to install modules without issue.
**Screenshots**
![Image](https://github.com/user-attachments/assets/a7e7af93-8323-45a5-9eb8-28cb3e2f903f)

**Additional context**

🔔 Note: This ticket should address common considerations without including country-specific content. Please ensure all references are generic and applicable across various contexts.

**Comment by gonzalesedwin1123** [comment]
@celinenilla , I have completed checking this. It appears that the error in the SPMIS-QA instance that was fixed yesterday solved this issue. @anthonymarkQA can you confirm this. I tried installing the major SPMIS modules and I did not get the error.

**Comment by anthonymarkQA** [comment]
Findings: QA Passed
https://qa-sp-mis.newlogic.net/web/login

Able to install modules in QA SPMIS without errors  - pass
![image](https://github.com/user-attachments/assets/d5dff7ac-4f72-49de-85fc-6e17797cc19d)
